### ISSUE TITLE
Set verbosity and shell via command line flags

### ISSUE THREAD

**Issue by mtimkovich** [google/zx#16]
## Expected Behavior

- `-V` to turn off verbose output
- `-s SHELL` to set which shell to use.

and `--help` and `--version` while we're at it lol

## Actual Behavior
```
$ zx -h
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/maxtimkovich/notes/-h' imported from /Users/maxtimkovich/.asdf/installs/nodejs/14.16.0/.npm/lib/node_modules/zx/zx.mjs
    at finalizeResolution (internal/modules/esm/resolve.js:276:11)
    at moduleResolve (internal/modules/esm/resolve.js:699:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at Loader.import (internal/modules/esm/loader.js:165:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at file:///Users/maxtimkovich/.asdf/installs/nodejs/14.16.0/.npm/lib/node_modules/zx/zx.mjs:51:18
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by antonmedv** [comment]
Done.
