### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by bieganski** [google/zx#18]
Taking any `.mjs` script, or trying to run `$ zx` I'm having following error:

```
$ zx ./skrypt.mjs 
/usr/local/lib/node_modules/zx/zx.mjs:17
import {join, basename} from 'path'
       ^
SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

The only steps I peformed were to install `zx` using `npm`, as stated in README.

**Comment by antonmedv** [comment]
Update nodejs

**Comment by bieganski** [comment]
Indeed, it worked. Thanks!
