### ISSUE TITLE
Incompatibility with Node v14.8 - v14.12.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [google/zx#214]
## Expected Behavior

`zx` runs on Node v14.9 per the README.

## Actual Behavior

It gets the following error:

```
$ nvm use 14.9
Now using node v14.9.0 (npm v6.14.8)

$ ./node_modules/.bin/zx test.mjs
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:750:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

Where `test.mjs` is quite simple:

```
#!/usr/bin/env npx zx

console.log('hello world')
```

## Steps to Reproduce the Problem

1. `nvm install 14.9`
1. `zx` or `zx [some_simple_script.mjs]`

Problem is resolved by using Node >= 14.13.0.

## Specifications

- Version: 14.9
- Platform: macOS 10.14.6

**Comment by antonmedv** [comment]
I guess we need to bump our node requirement 
https://github.com/sindresorhus/globby/blob/main/package.json#L16
