### ISSUE TITLE
Installed minimum required node version 14.8 but version.js throws error

### ISSUE THREAD

**Issue by aquacode** [google/zx#23]
## Expected Behavior

Wrote test.mjs script and followed README -- should execute 

## Actual Behavior

import {version} from './version.js'
        ^^^^^^^
SyntaxError: The requested module './version.js' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from './version.js';
const {version} = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)

## Steps to Reproduce the Problem

1. Install node 14.8.0
1. Write test.mjs
1. Copy script sample from README

## Specifications

- Version: 1.1
- Platform: Mac OSX Big Sur

**Comment by aquacode** [comment]
Installed node 14.16.1 (latest LTS) and now the error is gone

I suppose README needs to update to specify the true minimum version required

**Comment by aquacode** [comment]
Nothing to do
