### ISSUE TITLE
Only file and data URLs are supported by the default ESM loader on Windows and Node 14.13 

### ISSUE THREAD

**Issue by ragingwind** [google/zx#233]
## Expected Behavior

Import modules well

## Actual Behavior

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:750:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
    at link (internal/modules/esm/module_job.js:50:36) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

with Node 14.13 cause this error but not with 14.14. The version in the README should be updated

## Steps to Reproduce the Problem

1. zx index.mjs
1.
1.

## Specifications

- Version: 4.2.0
- Platform: Windows, Node 14.13

**Comment by antonmedv** [comment]
What changed in 14.14?
