### ISSUE TITLE
Won't let be empty when greping on bash

### ISSUE THREAD

**Issue by EasyYannic** [google/zx#283]
## Expected Behavior
variable should be 0 or empty.

## Actual Behavior
throws error message:
$ echo "123" | grep foo
/Users/###/###/####/google-zx/node_modules/zx/dist/bundle.cjs:15261
        let output = new ProcessOutput({
                     ^
ProcessOutput [Error]:
    at /Users/###/###/####/google-zx/src/Scripts/jobs-running.ts:36:30
    exit code: 1
    at ChildProcess.<anonymous> (/Users/###/###/####/google-zx/node_modules/zx/dist/bundle.cjs:15261:22)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1062:16)
    at Socket.<anonymous> (node:internal/child_process:448:11)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at Pipe.<anonymous> (node:net:687:12)

## Steps to Reproduce the Problem

typescript:
let outp = await $`echo "123" | grep foo`;

## Specifications

- Version: 4.2.0
- Platform: Verified on Ubuntu 20.04 and MacOS

**Comment by EasyYannic** [comment]
my workaround atm: echo "123" | grep foo || true

**Comment by antonmedv** [comment]
You can use .pipe() with nothrow():

https://github.com/google/zx#nothrow
