### ISSUE TITLE
Error: the input device is not a TTY (TTY not needed)

### ISSUE THREAD

**Issue by gunta** [google/zx#407]
Related: https://github.com/google/zx/issues/191

## Expected Behavior
Using Google's Wireit which doesn't have nor needs a TTY

### package.json
```json
 "scripts": {
    "example": "wireit"
 },
"wireit": {
    "example": {
         "command": "zx script.js"
    }
```

script.js
```js
await $`sh somescript.sh`
```

## Actual Behavior

```
the input device is not a TTY
    at setupBackend (/Users/a12907/Documents/GitHub/dooer/scripts.js:86:10)
    exit code: 1
    at ChildProcess.<anonymous> (node_modules/.pnpm/zx@6.1.0/node_modules/zx/src/index.mjs:105:20)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:715:12)
```

**Comment by antonmedv** [comment]
Looks like tty symulation is out of zx scope.
