### ISSUE TITLE
Support Node 14

### ISSUE THREAD

**Issue by jakebailey** [google/zx#428]
## Expected Behavior

I can use zx with Node 14, an LTS version of Node that supports mjs.

## Actual Behavior

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises
    at Loader.builtinStrategy (internal/modules/esm/translators.js:285:11)
    at new ModuleJob (internal/modules/esm/module_job.js:43:26)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:58:21)
    at async Promise.all (index 2)
    at async link (internal/modules/esm/module_job.js:63:9) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
```

This codebase has always run fine for me on Node 14; it seems like this new `node:timers/promises` import is the only thing that's breaking it. `sleep` as a promise is pretty short to write a helper for by hand based on the [`d.ts` file for the module](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/timers/promises.d.ts). (ignoring the `options` node provides, which I don't see as being useful in this context):

```ts
function sleep<T = void>(delay?: number, value?: T): Promise<T> {
    return new Promise((resolve) => {
        setTimeout(() => {
            resolve(value as T);
        }, delay)
    })
}
```

(Maybe even a little overkill for what this repo uses `sleep` for.)

That, and the emit target could be one that's Node 14 compatible, e.g. es2020. I think that the async local storage should be [available in Node 14](https://nodejs.org/docs/latest-v14.x/api/async_hooks.html#async_hooks_class_asynclocalstorage), although its docs are in a different place (which obscures its pre-16 availability).

In my case, I'd like node 14 because I'm using `zx` as a scripting language to automate some work I'm doing on the TypeScript repo, and there, our volta setting pins node to Node 14 (I will look into changing this, though).

## Steps to Reproduce the Problem

1. Import zx in Node 14

## Specifications

- Version: 6.2.1
- Platform: Node 14 Linux

**Comment by antonmedv** [comment]
What about TS esm support?

Also globby requires >=16.0.0

Also current active LTS is 16.x. 

I think it will be impossible to support 14.

**Comment by jakebailey** [comment]
Node 14 has ESM support, which started at node 12.

Node 14 is still in LTS; it's 12 that left LTS last month.

As for globby, can it not be downgraded or replaced with a similar library that more closely matches Node's support window?

**Comment by antonmedv** [comment]
IDK.

**Comment by jakebailey** [comment]
Looking back at globby, it supports node 12+, so I don't think that's an issue.

**Comment by antonmedv** [comment]
Hmm, well. If you will able to fix all issues for 14.x in PR - 👌

**Comment by antonmedv** [comment]
Well, looks like this issue not going to be done any time soon) 

Feel free to reopen the issue.
