### ISSUE TITLE
I have a sed that I am having trouble understanding where zx is upset. 

### ISSUE THREAD

**Issue by jacobnash** [google/zx#476]
I am running into an error where I believe zx is overriding my escapes. I don't know where I would start to unravel this one. 

## Expected Behavior

I am running this : await $`sed -rn 's/archName = "(.*)"/\1/p'   ./dist/build.file`

the sed command works. 

it should return something like aarch64

## Actual Behavior

I get this error:

     Proxy.set (file:///C:/Users/JacobNash/AppData/Roaming/npm/node_modules/zx/build/core.js:56:15)
    at file:///C:/dev/buildzx.mjs:6:22
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async importPath (file:///C:/Users/JacobNash/AppData/Roaming/npm/node_modules/zx/build/cli.js:143:5)
    at async main (file:///C:/Users/JacobNash/AppData/Roaming/npm/node_modules/zx/build/cli.js:79:9)
    at async file:///C:/Users/JacobNash/AppData/Roaming/npm/node_modules/zx/build/cli.js:24:1

## Steps to Reproduce the Problem

1. create  a mjs file 
2. add let foo = $`sed -rn 's/archName = "(.*)"/\1/p'   ./dist/build.file`

## Specifications

- Version: 7.0.7
- Platform: Windows.

**Comment by jacobnash** [comment]
well adding replacing \1 with \\1 seems to fix it.
