### ISSUE TITLE
Compat with vitest

### ISSUE THREAD

**Issue by natew** [google/zx#482]
## Expected Behavior

Importing in an otherwise empty vitest test file yields:

```
ReferenceError: Cannot access '$' before initialization
    at AsyncHook.syncCwd (file:///Users/n8/tamagui/node_modules/zx/build/core.js:301:5)
    at emitHook (node:internal/async_hooks:233:38)
    at promiseResolveHook (node:internal/async_hooks:365:3)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async VitestRunner.interopedImport (file:///Users/n8/tamagui/node_modules/vitest/dist/chunk-vite-node-utils.8077cd3c.mjs:1303:17)
    at async VitestRunner.directRequest (file:///Users/n8/tamagui/node_modules/vitest/dist/chunk-vite-node-utils.8077cd3c.mjs:1233:19)
    at async VitestRunner.cachedRequest (file:///Users/n8/tamagui/node_modules/vitest/dist/chunk-vite-node-utils.8077cd3c.mjs:1185:12)
    at async _VitestMocker.request (file:///Users/n8/tamagui/node_modules/vitest/dist/chunk-vite-node-utils.8077cd3c.mjs:1208:21)
```

## Actual Behavior

Should run

## Steps to Reproduce the Problem

In test.ts:

```
import { $ } from 'zx'
```

Then run: `npx vitest --run test.ts`

**Comment by gajus** [comment]
Still getting this on Windows

https://github.com/gajus/turbowatch/actions/runs/4465736367/jobs/7843101020?pr=21#step:5:14

Is there something that needs to be done locally to make it work?
