### ISSUE TITLE
cli args won't get through zx to the actual script

### ISSUE THREAD

**Issue by nnaku** [google/zx#510]
script file
```
#!/usr/bin/env zx
console.log(process.argv)
```

## Expected Behavior
before v 7.0.0
```
❯ script -e test
[
  '.../node',
  '.../zx',
  '.../script',
  '-e',
  'test'
]
```

## Actual Behavior
after v 7.0.0
```
❯ script -e test
ReferenceError: test is not defined
    at file:///private/var/folders/33/_b2gpxk957700696p70fqc600000gn/T/oezm4h430ml.mjs:1:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async importPath (file:///Users/.../node_modules/zx/build/cli.js:145:5)
    at async writeAndImport (file:///Users/.../node_modules/zx/build/cli.js:128:5)
    at async runScript (file:///Users/.../node_modules/zx/build/cli.js:96:5)
    at async main (file:///Users/.../node_modules/zx/build/cli.js:55:9)
    at async file:///Users/.../node_modules/zx/build/cli.js:24:1
```

## Specifications

- Version: 7.0.8
- Platform: macOS Moneterey 12.5.1 (intel)

**Comment by antonmedv** [comment]
https://github.com/google/zx#executing-scripts-via---eval
