### ISSUE TITLE
Failing to run child processes on Windows

### ISSUE THREAD

**Issue by gaui** [google/zx#570]
Version: 7.1.1

When running this on Windows:

```js
await $`git rev-parse --short HEAD`
```

I get the following error:

```
file:///C:/Users/gaui/git/cli/node_modules/zx/build/core.js:146
            let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
                         ^
 
ProcessOutput [Error]:
    at getGitSHA (file:///C:/Users/gaui/git/cli/dist/shared/shared.js:25:23)
    exit code: 1
    at ChildProcess.<anonymous> (file:///C:/Users/gaui/git/cli/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
  _code: 1,
  _signal: null,
  _stdout: '',
  _stderr: '',
  _combined: ''
```

When I print out $.shell I get: `C:\WINDOWS\System32\bash.EXE`

**Comment by antonmedv** [comment]
This is because if exit code is 1.

**Comment by gaui** [comment]
No it's not, it's related to what shell is being selected.

```js
import { $ } from 'zx';
let output = await $`git rev-parse --short HEAD`;
console.log(output);
```

Output:

```
$ git rev-parse --short HEAD
file:///C:/Users/gaui/git/cli/node_modules/zx/build/core.js:146
            let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
                         ^

ProcessOutput [Error]:
    at file:///C:/Users/gaui/git/cli/dist/cli.js:3:21
    exit code: 1
    at ChildProcess.<anonymous> (file:///C:/Users/gaui/git/cli/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1093:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
  _code: 1,
  _signal: null,
  _stdout: '',
  _stderr: '',
  _combined: ''
}
```

**Comment by antonmedv** [comment]
Zx trying to get bash from PATH by default. 

What shell zx, should select on windows?

**Comment by gaui** [comment]
I don't know, some that can run commands like `git rev-parse --short HEAD` and get the stdout? I'm not sure why but the `C:\WINDOWS\system32\bash.EXE` is not working. Maybe related to #532 ?

**Comment by gaui** [comment]
And also related to #523 ?
