### ISSUE TITLE
Awkward behavior on error with pipe

### ISSUE THREAD

**Issue by mighty1231** [google/zx#640]
single `exit 1` process - throws error

`exit 1` process with piped - does not throw error

Is it intended behavior?

```javascript
async function checkPipe() {
  try {
    await $`exit 1`.pipe($`echo hello`);
    console.log("not error at first");
  } catch (e) {
    console.log("it does not reach here (1)");
  }

  try {
    await $`exit 1`;
    console.log("it does not reach here (2)");
  } catch (e) {
    console.log("error catched!");
  }
}

await checkPipe();
```

## Expected Stdout

```
$ exit 1
$ echo hello
hello
it does not reach here (1)
error catched!
```

## Actual Behavior

```
$ exit 1
$ echo hello
hello
not error at first
file:///wd/temp.ts:106
    await $`exit 1`.pipe($`echo hello`);
           ^
ProcessOutput [Error]: 
    at checkPipe (file:///wd/temp.ts:106:12)
    exit code: 1
    at ChildProcess.<anonymous> (file:///wd/node_modules/zx/build/core.js:146:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:301:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {
  _code: 1,
  _signal: null,
  _stdout: '',
  _stderr: '',
  _combined: ''
}
```

## Specifications

- Version: 7.2.2
- Platform: Linux (Ubuntu 18.04)

**Comment by tymnec** [comment]
Can I work on this?

**Comment by antongolub** [comment]
Well, the queue is pretty clear:
1. <code>$\`exit 1\`</code> creates the first delayed action (setImmediate)
2. <code>$\`echo hello\`</code> creates the first second
3. The `pipe` method bounds processes via internal post / prerun hooks.
4. Then the 1st deferred `setImmediate` triggers internal `_run`, it fails and drowns the bound `dest._prerun = this.run.bind(this)`.

I think, _this is fine_. Just imagine a case, when some piped process awaits for the input and meets `exit 1` (like `cat`). I'd expect it to fall.

**Comment by mighty1231** [comment]
@antonmedv Is it fine that none of the log executed after the **second $ call**?

neither these logs shown

- `it does not reach here (2)`
- `error catched!`

### case 1 (normal)

just a single $ statement handles exception in nice way

```js
import { $ } from "zx/core";

async function checkPipe() {
  try {
    await $`exit 1`;
    console.log("it does not reach here (2)");
  } catch (e) {
    console.log("error catched!");
  }
}

await checkPipe();
```

result

```bash
$ node abc.mjs 2>/dev/null
error catched!
```

### case 2 (weird)

```js
import { $ } from "zx/core";

async function checkPipe() {
  try {
    await $`exit 1`.pipe($`echo hello`);
  } catch (e) {
    // do nothing
  }

  console.log('good');

  try {
    await $`exit 1`;
    console.log("it does not reach here (2)");
  } catch (e) {
    console.log("error catched!");
  }
}

await checkPipe();
```

result

```bash
$ node abc.mjs 2>/dev/null
good
```

**Comment by antongolub** [comment]
https://github.com/nodejs/promises-debugging/issues/16
