### ISSUE TITLE
Setting stdio/err to inherit throws error

### ISSUE THREAD

**Issue by thezzisu** [google/zx#771]
## Expected Behavior
```ts
$`ls`.stdio('inherit', 'inherit', 'inherit')
```
do not throw

## Actual Behavior

```ts
$`ls`.stdio('inherit', 'inherit', 'inherit')
```
throws with

```
ProcessOutput {
  stdout: '',
  stderr: '',
  signal: null,
  exitCode: null
}
```

Actually the real error is hidden which is
```
TypeError: Cannot read properties of null (reading 'pipe')
    at file:///home/thezzisu/Workspace/thezzisu/x/apps/cli/node_modules/zx/build/vendor.js:20380:22
    at Object.run (file:///home/thezzisu/Workspace/thezzisu/x/apps/cli/node_modules/zx/build/core.js:185:20)
    at invoke (file:///home/thezzisu/Workspace/thezzisu/x/apps/cli/node_modules/zx/build/vendor.js:20359:9)
    at exec (file:///home/thezzisu/Workspace/thezzisu/x/apps/cli/node_modules/zx/build/vendor.js:20429:21)
    at _ProcessPromise.run (file:///home/thezzisu/Workspace/thezzisu/x/apps/cli/node_modules/zx/build/core.js:173:18)
    at Immediate.callback [as _onImmediate] (file:///home/thezzisu/Workspace/thezzisu/x/apps/cli/node_modules/zx/build/core.js:101:56)
    at process.processImmediate (node:internal/timers:478:21)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
```

## Steps to Reproduce the Problem

1. Run `node`
1. Run `await import('zx/globals')`
1. Run ``$`ls`.stdio('inherit', 'inherit', 'inherit')``

## Specifications

- Version: 8.0.0
- Platform: Linux (However this is platform-independent)

Linked: https://github.com/webpod/zurk/issues/5

**Comment by thezzisu** [comment]
Something interesting:

The type here

https://github.com/webpod/zurk/blob/6a8b0086829a7c82ee35a68e394e50d2948b2b70/src/main/ts/spawn.ts#L46

forces stdio to be all `pipe`, even zx uses `inherit` `pipe` `pipe` by default (which is ignored using a any convertion).
